server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${ORDER_DB_USER:app}
    password: ${ORDER_DB_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-super-secret-demo-key-change-me}
  clients:
    product-service:
      base-url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

