server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${AUTH_DB_USER:root}
    password: ${AUTH_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET:kNf3s6Z1kF0Jq9wzXx+q0nA2p8bLzRkF4CkY0e6A9kM=}
      issuer: ${JWT_ISSUER:ecommerce}
      access-token-ttl-minutes: ${JWT_TTL_MINUTES:120}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

