server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${PRODUCT_DB_USER:root}
    password: ${PRODUCT_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-super-secret-demo-key-change-me}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

