import { db } from '@/db';
import { words } from '@/db/schema';

async function main() {
    const sampleWords = [
        {
            hanzi: '你好',
            pinyin: 'nǐ hǎo',
            translation: 'hello',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/你好/400/300',
            audioUrl: 'https://example.com/audio/你好.mp3',
            videoUrl: 'https://example.com/video/你好.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '谢谢',
            pinyin: 'xièxie',
            translation: 'thank you',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/谢谢/400/300',
            audioUrl: 'https://example.com/audio/谢谢.mp3',
            videoUrl: 'https://example.com/video/谢谢.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '妈妈',
            pinyin: 'māma',
            translation: 'mother',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/妈妈/400/300',
            audioUrl: 'https://example.com/audio/妈妈.mp3',
            videoUrl: 'https://example.com/video/妈妈.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '爸爸',
            pinyin: 'bàba',
            translation: 'father',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/爸爸/400/300',
            audioUrl: 'https://example.com/audio/爸爸.mp3',
            videoUrl: 'https://example.com/video/爸爸.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '苹果',
            pinyin: 'píngguǒ',
            translation: 'apple',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/苹果/400/300',
            audioUrl: 'https://example.com/audio/苹果.mp3',
            videoUrl: 'https://example.com/video/苹果.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '香蕉',
            pinyin: 'xiāngjiāo',
            translation: 'banana',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/香蕉/400/300',
            audioUrl: 'https://example.com/audio/香蕉.mp3',
            videoUrl: 'https://example.com/video/香蕉.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '鸡蛋',
            pinyin: 'jīdàn',
            translation: 'egg',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/鸡蛋/400/300',
            audioUrl: 'https://example.com/audio/鸡蛋.mp3',
            videoUrl: 'https://example.com/video/鸡蛋.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '牛奶',
            pinyin: 'niúnǎi',
            translation: 'milk',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/牛奶/400/300',
            audioUrl: 'https://example.com/audio/牛奶.mp3',
            videoUrl: 'https://example.com/video/牛奶.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '面包',
            pinyin: 'miànbāo',
            translation: 'bread',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/面包/400/300',
            audioUrl: 'https://example.com/audio/面包.mp3',
            videoUrl: 'https://example.com/video/面包.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '咖啡',
            pinyin: 'kāfēi',
            translation: 'coffee',
            difficulty: 'easy',
            imageUrl: 'https://picsum.photos/seed/咖啡/400/300',
            audioUrl: 'https://example.com/audio/咖啡.mp3',
            videoUrl: 'https://example.com/video/咖啡.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '朋友',
            pinyin: 'péngyǒu',
            translation: 'friend',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/朋友/400/300',
            audioUrl: 'https://example.com/audio/朋友.mp3',
            videoUrl: 'https://example.com/video/朋友.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '同学',
            pinyin: 'tóngxué',
            translation: 'classmate',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/同学/400/300',
            audioUrl: 'https://example.com/audio/同学.mp3',
            videoUrl: 'https://example.com/video/同学.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '老师',
            pinyin: 'lǎoshī',
            translation: 'teacher',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/老师/400/300',
            audioUrl: 'https://example.com/audio/老师.mp3',
            videoUrl: 'https://example.com/video/老师.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '学校',
            pinyin: 'xuéxiào',
            translation: 'school',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/学校/400/300',
            audioUrl: 'https://example.com/audio/学校.mp3',
            videoUrl: 'https://example.com/video/学校.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '餐厅',
            pinyin: 'cāntīng',
            translation: 'restaurant',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/餐厅/400/300',
            audioUrl: 'https://example.com/audio/餐厅.mp3',
            videoUrl: 'https://example.com/video/餐厅.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '超市',
            pinyin: 'chāoshì',
            translation: 'supermarket',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/超市/400/300',
            audioUrl: 'https://example.com/audio/超市.mp3',
            videoUrl: 'https://example.com/video/超市.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '书包',
            pinyin: 'shūbāo',
            translation: 'school bag',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/书包/400/300',
            audioUrl: 'https://example.com/audio/书包.mp3',
            videoUrl: 'https://example.com/video/书包.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '椅子',
            pinyin: 'yǐzi',
            translation: 'chair',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/椅子/400/300',
            audioUrl: 'https://example.com/audio/椅子.mp3',
            videoUrl: 'https://example.com/video/椅子.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '杯子',
            pinyin: 'bēizi',
            translation: 'cup',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/杯子/400/300',
            audioUrl: 'https://example.com/audio/杯子.mp3',
            videoUrl: 'https://example.com/video/杯子.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '喜欢',
            pinyin: 'xǐhuan',
            translation: 'to like',
            difficulty: 'medium',
            imageUrl: 'https://picsum.photos/seed/喜欢/400/300',
            audioUrl: 'https://example.com/audio/喜欢.mp3',
            videoUrl: 'https://example.com/video/喜欢.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '电脑',
            pinyin: 'diànnǎo',
            translation: 'computer',
            difficulty: 'hard',
            imageUrl: 'https://picsum.photos/seed/电脑/400/300',
            audioUrl: 'https://example.com/audio/电脑.mp3',
            videoUrl: 'https://example.com/video/电脑.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '衣服',
            pinyin: 'yīfu',
            translation: 'clothes',
            difficulty: 'hard',
            imageUrl: 'https://picsum.photos/seed/衣服/400/300',
            audioUrl: 'https://example.com/audio/衣服.mp3',
            videoUrl: 'https://example.com/video/衣服.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '鞋子',
            pinyin: 'xiézi',
            translation: 'shoes',
            difficulty: 'hard',
            imageUrl: 'https://picsum.photos/seed/鞋子/400/300',
            audioUrl: 'https://example.com/audio/鞋子.mp3',
            videoUrl: 'https://example.com/video/鞋子.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '太阳',
            pinyin: 'tàiyáng',
            translation: 'sun',
            difficulty: 'hard',
            imageUrl: 'https://picsum.photos/seed/太阳/400/300',
            audioUrl: 'https://example.com/audio/太阳.mp3',
            videoUrl: 'https://example.com/video/太阳.mp4',
            createdAt: new Date().toISOString(),
        },
        {
            hanzi: '月亮',
            pinyin: 'yuèliang',
            translation: 'moon',
            difficulty: 'hard',
            imageUrl: 'https://picsum.photos/seed/月亮/400/300',
            audioUrl: 'https://example.com/audio/月亮.mp3',
            videoUrl: 'https://example.com/video/月亮.mp4',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(words).values(sampleWords);
    
    console.log('✅ Words seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});